version: '3.9'

services:
  peer1:
    build:
      context: .
    container_name: peer1
    networks:
      p2p_network:
        ipv4_address: 10.10.10.101
    stdin_open: true
    tty: true

  peer2:
    build:
      context: .
    container_name: peer2
    networks:
      p2p_network:
        ipv4_address: 10.10.10.102
    stdin_open: true
    tty: true

  peer3:
    build:
      context: .
    container_name: peer3
    networks:
      p2p_network:
        ipv4_address: 10.10.10.103
    stdin_open: true
    tty: true

networks:
  p2p_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24